name: Update Glossario Hidra

on:
  schedule:
    - cron: '0 11 * * 1' # Segunda 08:00 UTC-3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 24 ainda é instável, usa 20 LTS

      - name: Install deps
        run: npm install

      - name: Build Glossario
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }} # Nome certo
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }} # Pega do Secret
        run: npm run build

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: jato de dados frescos $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
